---
Name: "ansible/playbook-templates"
Description: "Defines a list of playbook templates to run in Ansible Apply task"
Documentation: |
  This is an array of strings where each string is a template that renders
  an Ansible Playbook.  They are run in sequence to allow building inventory
  dynamically during a run.
Schema:
  type: "array"
  items:
    type: "string"

Meta:
  icon: "cog"
  color: "blue"
  title: "Community Content"
  copyright: "RackN 2019"
