---
Name: "add-demo-profile"
Description: "Add k3s-demo profile"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e

      curl -X POST \
        --user rocketskates:r0cketsk8ts \
        --insecure \
        -H "Content-Type: application/json" \
        -d '{"Name":"k3s-demo",
          "Description":"LOCAL Writable Profile for k3s build",
          "Params":{
            "krib/cluster-profile": "k3s-demo"
          },
          "Meta":{
            "icon":"ship",
            "color":"blue"
          }
        }' \
        https://{{ .Machine.Address }}:8092/api/v3/profiles

      exit 0

    Name: "k3s-demo"
Meta:
  icon: "spy"
  color: "purple"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
