---
Name: "ansible-apply"
Description: "A task run Ansible Templates"
Documentation: |
  Runs one or more Ansible Playbook templates as defined by the
  `ansible/playbook-templates` variable in the `ansible-apply` stage.

  Requires an `ansible` context.

  Information can be chained together by having the playbook
  write `[Machine.Uuid].json` as a file.  This will be saved on the
  machine as `Param.ansible/output` and then fed into the next
  Playbook as the `digitalrebar` variable so it is available.
RequiredParams:
  - ansible/playbook-templates
  - rsa/key-public
  - rsa/key-user
  - rsa/key-private
OptionalParams:
  - aws/access-key
  - aws/secret-key
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e

      {{template "setup.tmpl" .}}

      # we need a keypair for Ansible
      {{ if .ParamExists "rsa/key-private" }}
      echo "Retrieving SSH key from Machine Params rsa/key-*"
      tee rsa-{{.Machine.Name}} >/dev/null << EOF
      {{.Param "rsa/key-private"}}
      EOF
      tee rsa-{{.Machine.Name}}.pub >/dev/null << EOF
      {{.Param "rsa/key-public"}}
      EOF
      {{ else }}
      if [[ ! -e rsa-{{.Machine.Name}} ]]; then
        echo "Generating single use keypair for initialization"
        ssh-keygen -t rsa -N "{{.Machine.Uuid}}" -f "rsa-{{.Machine.Name}}"
      else
        echo "Using existing key: rsa-{{.Machine.Name}}.pub"
      fi
      echo "Saving local key to Machine $RS_UUID"
      ls -la
      drpcli machines set $RS_UUID param "rsa/key-private" to "\"$(cat rsa-{{.Machine.Name}})\""
      drpcli machines set $RS_UUID param "rsa/key-public" to "\"$(cat rsa-{{.Machine.Name}}.pub)\""
      drpcli machines set $RS_UUID param "rsa/key-user" to "ec2-user"
      {{ end }}

      {{ $machine := .Machine.Name -}}
      {{ range $index, $template := (.Param "ansible/playbook-templates") -}}
      {{ $playbook := printf "%s" $template -}}

      ## Build Playbook
      echo "============== Playbook {{$index}} =============="
      echo "Building from Template {{ $playbook }}"
      tee playbook.yaml >/dev/null << EOF
      {{$.CallTemplate $playbook $}}
      EOF

      ## Pull data for playbook from Machine
      ADDRESS=$(drpcli machines show $RS_UUID | jq -r .Address)
      if [[ "$ADDRESS" == "" ]]; then
        ADDRESS="localhost"
      else
        ADDRESS="$ADDRESS,"
      fi
      INPUT=$(drpcli machines show $RS_UUID)

      echo "Run Playbook {{$index}} using $(ansible-playbook --version)"
      ansible-playbook \
        -i $ADDRESS \
        -e digitalrebar="${INPUT}" \
        --private-key="rsa-{{$machine}}" \
        playbook.yaml

      # capture address (if any) from run
      if [[ -f {{$machine}}-address.txt ]]; then
        echo "Saving {{$machine}}-address.txt to Machine.Address"
        drpcli machines update $RS_UUID "{\"Address\":\"$(cat {{$machine}}-address.txt)\"}"
      else
        echo "No address file from Playbook.  If desired, create {{$machine}}-address.txt"
      fi

      # capture results from run
      if [[ -f {{$machine}}.json ]]; then
        echo "Saving Ouput from {{$machine}}.json to Machine.Paarams anisble/output."
        drpcli machines set $RS_UUID param ansible/output to "$(cat {{$machine}}.json)"
      else
        echo "No output file from Playbook.  If desired, create {{$machine}}.json"
      fi
      {{ end }}

      echo "Done"
    Name: "Run Playbooks"
Meta:
  icon: "map"
  color: "blue"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
