---
Description: "Return to using Runner Context"
Name: "context-runner"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e
      {{template "setup.tmpl" .}}

      # prepare machine for agent to take over
      drpcli machines meta set $RS_UUID key BaseContext to runner
    
      exit 0

    Name: "clear"
Meta:
  icon: "share"
  color: "black"
  title: "RackN"
  feature-flags: "sane-exit-codes"
