---
Description: "Clear Workflow and Context"
Name: "context-clear"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e
      {{template "setup.tmpl" .}}

      # prepare machine for agent to take over
      drpcli machines meta remove $RS_UUID key BaseContext

      exit 0

    Name: "clear"
Meta:
  icon: "eraser"
  color: "black"
  title: "RackN"
  feature-flags: "sane-exit-codes"
