---
Name: "dr-server-seed"
Description: "Setup Files for Digital Rebar Server"
Documentation: |
  Copy Files from Multi-Site-Manager to Local DR Server
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      # DO NOT INCLUDE template "setup.tmpl" !!

      {{ $addr := .Machine.Address -}}

      export RS_KEY="rocketskates:r0cketsk8ts"
      export RS_ENDPOINT="https://{{$addr}}:8092"
      unset RS_TOKEN

      echo "Pointing DRPCLI to $RS_ENDPOINT using $RS_KEY"

      drpcli -x profiles list

      echo "copy over Linode Token (value NOT shown)"
      drpcli -x profiles set global set "linode/token" to "{{ .Param "linode/token" }}" >/dev/null

      echo "copy over Linode Region to {{ .Param "linode/region" }}"
      drpcli -x profiles set global set "linode/region" to "{{ .Param "linode/region" }}" >/dev/null

      echo "copy over Prefix to {{ .Param "demo/cluster-prefix" }}"
      drpcli -x profiles set global set "demo/cluster-prefix" to "{{ .Param "demo/cluster-prefix" }}" >/dev/null

      exit 0

    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
