---
Name: "dr-server-seed"
Description: "Setup Files for Digital Rebar Server"
Documentation: |
  Copy Files from Multi-Site-Manager to Local DR Server
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      {{template "setup.tmpl" .}}

      {{ $url := .ProvisionerURL -}}
      {{ $addr := .Machine.Address -}}

      echo "copy over Linode Token"
      drpcli profiles -U rocketskates -P r0cketsk8ts -x -E https://{{$addr}}:8092 set global set "linode/token" to {{ .Param "linode/token" }} >/dev/null

      echo "copy over Linode Region"
      drpcli profiles -U rocketskates -P r0cketsk8ts -x -E https://{{$addr}}:8092 set global set "linode/region" to {{ .Param "linode/region" }} >/dev/null

      echo "copy over Prefix"
      drpcli profiles -U rocketskates -P r0cketsk8ts -x -E https://{{$addr}}:8092 set global set "demo/cluster-prefix" to {{ .Param "demo/cluster-prefix" }} >/dev/null

      exit 0

    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
