---
Name: "dr-server-install"
Description: "Install Digital Rebar Server"
Documentation: |
  Installs MINIMAL DRP assuming population by Multi-Site-Manager

  TODO: make user/password settable

  Requires install.sh and dr-provision.zip to be in DRP files/bootstrap

  Does nothing if DRP already installed

  If Manager installed, will register this DRP as an endpoint
ExtraClaims:
  - scope: "*"
    action: "*"
    specific: "*"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e
      {{template "setup.tmpl" .}}

      if [[ "$(systemctl is-active dr-provision)" != "active" ]] ; then

        echo "Download Components"
        drpcli files download "bootstrap/dr-provision.zip" > dr-provision.zip
        drpcli files download "bootstrap/install.sh" > install.sh
        chmod +x install.sh

        echo "DRP $action"
        unset RS_ENDPOINT
        ./install.sh install --systemd --drp-id={{ .Machine.Name }} --no-content --startup --zip-file=dr-provision.zip

      else
        echo "DRP already installed, skipping"
      fi

      if drpcli extended -l endpoints show {{ .Info.Id }} ; then
        if drpcli extended -l endpoints show {{ .Machine.Name }} ; then
          echo "Endpoint {{ .Machine.Name }} already registered"
        else
          echo "Registering {{ .Machine.Name }} for management"
          drpcli plugins runaction manager addEndpoint manager/url https://{{ .Machine.Address}}:8092 manager/username rocketskates manager/password r0cketsk8ts
        fi
      else
        echo "No Manager Plugin"
      fi

      exit 0

    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
