---
Name: "dr-server-install"
Description: "Install Digital Rebar Server"
Documentation: |
  Installs MINIMAL DRP assuming population by Multi-Site-Manager

  Requires access to the internet to download the installer.

  Future:
    * allow download from DRP
    * expand use of params
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e
      {{template "setup.tmpl" .}}
      
      action=install
      if [[ "$(systemctl is-active dr-provision)" == "active" ]] ; then
        echo "dr-provision found running, performing an upgrade"
        systemctl stop dr-provision
        action=upgrade
      fi

      echo "Download Components"
      drpcli files download "bootstrap/v4drp-install.zip" > v4drp-install.zip
      drpcli files download "bootstrap/install.sh" > install.sh
      chmod +x install.sh

      echo "DRP $action"
      unset RS_ENDPOINT
      ./install.sh $action --systemd --drp-id={{ .Machine.Name }} --no-content --startup --zip-file=v4drp-install.zip

      exit 0

    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
