---
Name: "dr-server-register"
Description: "Register Digital Rebar Server Endpoints"
Documentation: |
  If Manager installed, will register this DRP as an endpoint
ExtraClaims:
  - scope: "*"
    action: "*"
    specific: "*"
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      {{template "setup.tmpl" .}}

      {{ $drpid := (regexFind "[a-zA-Z0-9-]+" .Machine.Name) }}
      RS_USER="rocketskates"
      RS_PASS="r0cketsk8ts"

      if drpcli extended -l endpoints exists {{ .Info.Id }} ; then
        if drpcli extended -l endpoints show {{ $drpid }} ; then
          echo "Endpoint {{ $drpid }} already registered"
        else
          echo "Registering {{ $drpid }} for management"
          drpcli plugins runaction manager addEndpoint manager/url https://{{ .Machine.Address}}:8092 manager/username $RS_USER manager/password $RS_PASS
        fi
      else
        echo "No Manager Plugin"
      fi

      exit 0

    Name: "drp-register"
Meta:
  icon: "chess"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
