---
Name: "dr-server-seed"
Description: "Setup Files for Digital Rebar Server"
Documentation: |
  Copy Files from Multi-Site-Manager to Local DR Server
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2020

      set -e
      # DO NOT INCLUDE template "setup.tmpl" !!

      drpcli contexts show runner > runner.json

      {{ $addr := .Machine.Address -}}

      export RS_KEY="rocketskates:r0cketsk8ts"
      export RS_ENDPOINT="https://{{$addr}}:8092"
      unset RS_TOKEN
      unset RS_LOCAL_PROXY

      echo "Pointing DRPCLI to $RS_ENDPOINT using $RS_KEY"

      drpcli -x profiles show global

      echo "copy over Linode Token (value NOT shown)"
      drpcli -x profiles set global set "linode/token" to "{{ .Param "linode/token" }}" >/dev/null

      echo "copy over Linode Region to {{ .Param "linode/region" }}"
      drpcli -x profiles set global set "linode/region" to "{{ .Param "linode/region" }}" >/dev/null

      echo "copy over Prefix to {{ .Param "demo/cluster-prefix" }}"
      drpcli -x profiles set global set "demo/cluster-prefix" to "{{ .Param "demo/cluster-prefix" }}" >/dev/null

      if drpcli contexts exists runner ; then
        echo "runner context already installed"
      else
        echo "adding local runner context"
        drpcli -x contexts create - < runner.json
      fi

      echo "Populate the contexts"
      raw=$(drpcli contexts list Engine=docker-context)
      contexts=$(jq -r ".[].Name" <<< "${raw}")
      i=0
      for context in $contexts; do
        image=$(jq -r ".[$i].Image" <<< "${raw}")
        echo "Installing Container for $context named from $image"
        drpcli files upload {{ .ProvisionerURL }}/files/contexts/docker-context/${image} as contexts/docker-context/${image}
        drpcli plugins runaction docker-context imageUpload \
          context/image-name ${image} \
          context/image-path files/contexts/docker-context/${image}
        i=$(($i + 1))
      done

      exit 0
    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
