---
Name: "dr-server-install"
Description: "Install Digital Rebar Server"
Documentation: |
  Installs MINIMAL DRP assuming population by Multi-Site-Manager

  Requires install.sh and v4drp-install.zip to be in DRP files/bootstrap

  Does nothing if DRP already installed
Templates:
  - Contents: |-
      #!/bin/bash
      # RackN Copyright 2019

      set -e
      {{template "setup.tmpl" .}}
      
      if [[ "$(systemctl is-active dr-provision)" != "active" ]] ; then

        echo "Download Components"
        drpcli files download "bootstrap/v4drp-install.zip" > v4drp-install.zip
        drpcli files download "bootstrap/install.sh" > install.sh
        chmod +x install.sh

        echo "DRP $action"
        unset RS_ENDPOINT
        ./install.sh install --systemd --drp-id={{ .Machine.Name }} --no-content --startup --zip-file=v4drp-install.zip

      else
        echo "DRP already installed, skipping"
      fi

      exit 0

    Name: "drp-install"
Meta:
  icon: "heart"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
